### PR TITLE
SSE optimizations for 5x5 convolution.

### PR DESCRIPTION
**Pull request by zakattacktwitter**
This is a pretty specific optimization to Twitter's usage of 5x5 but it could be extended to support more sizes in the future.

### CODE REVIEW

**Comment by zakattacktwitter** [comment]
Does anyone have any opinions on this? We also have a fast-path for 3x3 convolutions.

**Comment by soumith** [comment]
no opinion. it looks good!
Would love to have 3x3 as well.
Thanks for putting it in the generic/simd folder. That makes it clear (unlike THVector.h).

**Comment by clementfarabet** [comment]
Great, let's add the 3x3 kernels in then.

**Comment by andresy** [comment]
More or less same comment than Soumith': looks great, would love to have more like those. The simd directory is indeed a good idea. The only question is do we want this in the core, or as a package (like simd ;))?

**Comment by dominikgrewe** [comment]
I think it's great too! Some tests would be good. And can we hook this up to Lua somehow?

I don't understand why the code is in the "generic" folder though if it's only for float.

**Comment by soumith** [comment]
@dominikgrewe it looks like both Float and Double.

**Comment by soumith** [comment]
or extendable to be so. because the sse instructions are macro-templated as well.

**Comment by clementfarabet** [comment]
The macros are Float only actually, that's right. I guess we put them in generic because they're loaded by THTensorConv, and we prob want to have a double version at some point. 

Also we only did 3x3 and 5x5 because it's the only two kernels we use for everything.

**Comment by soumith** [comment]
I'll give the final merge call on this to @andresy , this will establish our directory and file structure for pushing SIMD optimizations going forward, so needs a bit of thought.

**Comment by soumith** [comment]
these aren't hooked into the lua side yet seems like it... coming in a later PR?

**Pull request merged**
