### PR TITLE
Add isSize method for Tensors.

### PR DESCRIPTION
**Pull request by timharley**

### CODE REVIEW

**Comment by timharley** [comment]
What are your thoughts @soumith @korayk?

**Comment by koraykv** [comment]
I am good, maybe the name hasSize is better?

**Comment by soumith** [comment]
sizeIs is good, isSize is also good (goes with isSameSizeAs), hasSize is also good, sizeEquals is good as well.

**Comment by andresy** [comment]
I am not the English native speaker there, I let you guys choose. I can also think about isOfSize()

**Comment by timharley** [comment]
+1 for `:isSize(size)`, but they all work really. Does anybody have a strong preference?

**Comment by soumith** [comment]
@timharley looks like not, change it to one of the options above if you'd like and we can wrap it up.

**Comment by timharley** [comment]
I've amended the commit to add `isSize`, should be good to merge.

**Pull request merged**
