### PR TITLE
First update of math.md

### PR DESCRIPTION
**Pull request by Atcold**
Yes, I know I'm affected by OCD...
Cleaned up to `clamp()`, which was missing proper formula layout.

### CODE REVIEW

**Comment by soumith** [comment]
could you squash your commits

**Comment by Atcold** [comment]
Sure, I was planning to finish the whole file cleaning first... I hope I won't run into conflicts if someone else is going to update it as well...

**Comment by Atcold** [comment]
Done, you're good to merge.

**Comment by soumith** [comment]
Thanks.

**Comment by Atcold** [comment]
Sure :+1:

**Pull request merged**
