### PR TITLE
Fixing torch.gels in the underdetermined case.

### PR DESCRIPTION
**Pull request by yozw**
The torch.gels function threw a lapack error when calling it with an underdetermined system, i.e., the case m < n. As discussed with @koraykv, I have fixed this and added tests.

### CODE REVIEW

**Comment by soumith** [comment]
Thank you. Can you please squash your commits to a single commit and I will merge it in after a test.

**Comment by yozw** [comment]
Done. With thanks to @jucor.

**Comment by yozw** [comment]
BTW, maybe let's give @koraykv the opportunity to comment before merging this.

**Comment by jucor** [comment]
Always happy to help, @yozw :) Thanks for your work fixing this tricky bug!

**Comment by koraykv** [comment]
Cool, this looks good to me. Thanks a lot!

**Pull request merged**
