### PR TITLE
fix uninitialized variable in cmake FindSSE

### PR DESCRIPTION
**Pull request by elikosan**
Leaving the variable uninitialized causes the program to crash on Windows

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
@elikosan Can you rebase to one commit?

**Comment by elikosan** [comment]
Sorry for the newbie question... is this the right resource to understand how to use rebase in this context ? https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request
Thanks

**Comment by soumith** [comment]
thanks Eric!

**Comment by nicholas-leonard** [comment]
@elikosan I like to use :
```
git checkout master
git pull upstream master
git checkout mybranch
git rebase -i master
[s: squash all commits but the first]
[make a nice commit message]
git push -f origin mybranch
```

**Pull request merged**
