### PR TITLE
readthedocs

### PR DESCRIPTION
**Pull request by nicholas-leonard**
This PR results in this http://torch7.readthedocs.org/en/readthedocs/tensor/index.html .

### CODE REVIEW

**Comment by soumith** [comment]
cool stuff!!!!!!!!

**Comment by szagoruyko** [comment]
this has broken ```help(torch.*)``` doc printing.

**Comment by nicholas-leonard** [comment]
@szagoruyko did you try updating the dok package?

**Comment by szagoruyko** [comment]
@nicholas-leonard works now, thanks.

**Pull request merged**
