### PR TITLE
Fix contiguous assertion in View implementation

### PR DESCRIPTION
**Pull request by karthikncode**
Replace the assertion in View implementation with automatic cloning if tensor not contiguous.

### CODE REVIEW

**Comment by fmassa** [comment]
Hum, I wonder if this is the desired behaviour.
There is an assumption that `:view` returns a view of the same storage, so cloning it might lead to unwanted behaviour at some places.

**Comment by karthikncode** [comment]
Not sure if it breaks anything, but I was getting the assertion error with nn.View otherwise.

**Comment by karthikncode** [comment]
Ah, I see. So maybe not a global change then?

**Comment by fmassa** [comment]
Can't you use a `nn.Contiguous` before `nn.View`?

**Comment by karthikncode** [comment]
Ah - didn't realize there was one for that. Sorry about that!

**Pull request closed without merging**
