### PR TITLE
torch.HalfTensor mostly working

### PR DESCRIPTION
**Pull request by borisfom**
@soumith, @szagoruyko , @ngimel:
Here, first cut, as we discussed in https://github.com/torch/cutorch/issues/484.
Math for HalfTensor should be extended later - only for ARM and other CPUs with native __fp16 type.

### CODE REVIEW

**Comment by ngimel** [comment]
torch.HalfTensor will also have to be added to cutorch, in particular Tensor.lua and generic/CTensor.c

**Comment by borisfom** [comment]
@ngimel : absolutely! I am also preparing to push a commit with (temporary) config switches so that the rest of modules build.

**Comment by borisfom** [comment]
@soumith: I think I have fixed it all as of commit 84d766c, should be ready to go!

**Comment by borisfom** [comment]
@soumith: actually, please hold on on merging this: after intergrating with cutorch I think the type should go into cwrap to avoid duplication (torch's torchcwrap is not exported). Also the C type name should be the same - not so hard to do.

**Comment by borisfom** [comment]
@soumith: it you think we should leave cwrap alone, then I suppose, exporting torchcwrap is in order - please let me know!

**Comment by soumith** [comment]
i think the type being here is fine. it's not a fundamental type and does not have to go into cwrap.

**Comment by borisfom** [comment]
@soumith : right, I reached the same conclusion about the location of 'half' - should be in pkg/torch.
I am finishing my tweaks to use the same type name - it looks cleaner and let us avoid a few dummy type conversions, but it's a bit more tedious as I can't simply move it from cutorch as it relies on CUDA header so the definition needs to be conditional depending of where THHalf.h is included from.

**Comment by soumith** [comment]
cc: @gchanan

**Comment by borisfom** [comment]
Superceded by https://github.com/torch/torch7/pull/826

**Pull request closed without merging**
