### PR TITLE
Exposing the lapack function potrs and extending torch.potrf() to take optional uplo character argument

### PR DESCRIPTION
**Pull request by j-wilson**

### CODE REVIEW

**Comment by koraykv** [comment]
Can you squash your commits please.

**Comment by j-wilson** [comment]
Sure, should be squashed now.

**Comment by koraykv** [comment]
Sorry I did not catch this the first time, can you actually keep the original potrf test please, the case where uplo argument is not passed.

**Comment by j-wilson** [comment]
Sure; should I be keeping both then?

**Comment by j-wilson** [comment]
I've added the original test back in; and, renamed the updated version torchtest.testCholesky_uplo. Please let me know whether there are any further changes you would like to see.

**Comment by koraykv** [comment]
thanks, looks good to me. @soumith if you also like let's merge

**Comment by j-wilson** [comment]
@soumith Please let me know whether there are any additional changes you'd like to see; I'm waiting to

**Comment by soumith** [comment]
lgtm :) thanks james.

**Pull request merged**
