### PR TITLE
parallel build => builds faster

### PR DESCRIPTION
**Pull request by hughperkins**
parallel build => builds faster

### CODE REVIEW

**Comment by hughperkins** [comment]
(fixed minor buggette in positioning of `-j` option)

**Comment by soumith** [comment]
this needs to have a Windows fallback, like here:
https://github.com/torch/cutorch/blob/master/rocks/cutorch-scm-1.rockspec

**Comment by hughperkins** [comment]
Ah, thats interesting, considering the comment I just made in the 'static libraries' PR :-D  Ok, will take a look.

**Comment by hughperkins** [comment]
(Pushed update, which removes the parallel code, on Windows)

**Comment by soumith** [comment]
thanks Hugh!

**Comment by hughperkins** [comment]
Thanks! :-)

**Pull request merged**
