### PR TITLE
Exposing the lapack function trtrs which solves triangular systems of linear equations.

### PR DESCRIPTION
**Pull request by yozw**
Lapack has optimized functions for solving systems of equations Ax = b in which the matrix A is upper- or lower-triangular. This pull request exposes this function through a new function torch.trtrs.

### CODE REVIEW

**Comment by soumith** [comment]
hey @yozw , the unit test you added seems to be failing: https://travis-ci.org/torch/torch7/jobs/73904453

**Comment by yozw** [comment]
Yes, i'm not sure what went wrong there: some strings had an extra space in them. I've fixed it. The latest version should have passing tests.

**Comment by soumith** [comment]
thanks. I think looks good. cc: @koraykv

**Comment by koraykv** [comment]
Yes, looks good, thanks Soumith.

**Comment by yozw** [comment]
Thanks, Soumith.

**Pull request merged**
