### PR TITLE
New function longSize for files

### PR DESCRIPTION
**Pull request by mvitez**
This function allows binary files compatibility between 32 and 64 bit
architectures.

The only difference between 32 and 64 bit architectures is the size of the C type long. By specifying the size of long in binary files, binary files can be read back on different architectures, in the same way as bigEndianEncoding() and littleEndianEncoding() allow to exchange files between architectures with same size, but different endianness.

### CODE REVIEW

**Comment by soumith** [comment]
oooh nice! I suppose this solves: https://github.com/torch/torch7/issues/5

**Comment by soumith** [comment]
is this backward compatible?

**Comment by mvitez** [comment]
Yes, it solves that issue, as that issue has nothing to do with endianness (ARMs are normally configured to work little endian, even if they can work in both modes).

This function has maximum backward compatibility, as it allows to work in three modes: use 4 byte longs, use 8 byte longs, use system default (default, as it it's now).

**Comment by soumith** [comment]
Thanks a lot Marko. Very clean and nicely done.

**Comment by mvitez** [comment]
Great. Thank you.

**Comment by Atcold** [comment]
Should we include this into `torch.load()` and `torch.save()`, or it is considered an option for advanced users only? For example
```lua
torch.save(filename, object [, format, referenced])
[object] torch.load(filename [, format, referenced])
```
and if `format` can take `string` or `binary`, as usual, plus  `long=0` (standard binary), `long=4` and `long=8`.
I can try to implement it, @soumith, if you're OK.

**Comment by soumith** [comment]
there seem to be no major takers for this. I think we will keep it at the file level for now and not include torch.load / torch.save

**Comment by Atcold** [comment]
Hmm... I'm not sure there are no major takers.
Anyone who switches between 32 and 64 bit OS is going to face this annoying problem.
Let's add a `torch.load32()` and `torch.load64()` which automates the conversion.

**Comment by mvitez** [comment]
:+1:

**Comment by culurciello** [comment]
+1 yes this would make all our lives a lot easier please guys!

**Comment by culurciello** [comment]
+1

**Comment by Atcold** [comment]
Merged here #579.

**Pull request merged**
