### PR TITLE
Add table of content to each README

### PR DESCRIPTION
**Pull request by johnny5550822**
Add table of content (by doctoc) to improve documentation navigation.

### CODE REVIEW

**Comment by soumith** [comment]
I'll let @nicholas-leonard review this, he is doing some documentation revamp.

**Comment by nicholas-leonard** [comment]
This is kind of redundant to the [readthedocs](http://torch7.readthedocs.org/en/rtd/maths/index.html) documentation as an auto-generated table of contents is already provided on the left pane. Let me test how the rtd site would look with this change.

**Comment by nicholas-leonard** [comment]
This is what it would look like on readthedocs : http://torch-test.readthedocs.org/en/latest/tensor/index.html ...

**Comment by johnny5550822** [comment]
Yes...I am just thinking when people navigate the readme in the github page for torch7/nn/other packages; it may be easier for them to look at what there are corresponding to a README.

So people should refer to readthedocs  than the one in github? Seem like the document structures are different in two of them.

**Comment by soumith** [comment]
hi @johnny5550822 ! thanks a lot for spending the time on Table of Contents. We are transitioning to be completely on readthedocs and it will finish soon. After that people will just refer to readthedocs than the github.

So considering that this does not go greatly with readthedocs, i am going to close the issue at the moment.

**Comment by johnny5550822** [comment]
Sounds good to me. Looking forward for it!

**Pull request closed without merging**
