### PR TITLE
Added indexAdd

### PR DESCRIPTION
**Pull request by ajabri**
Added function 'indexAccum' that is similar to 'indexCopy' but instead of setting each value by index in dest, it adds the value to the existing value at the index in dest.

### CODE REVIEW

**Comment by soumith** [comment]
could you add documentation in ./doc/tensor.md

**Comment by andresy** [comment]
shouldn't it be indexAdd? We do not have any Accum elsewhere...

**Comment by lvdmaaten** [comment]
Hmmm yeah `indexAdd` makes sense I suppose. As long as it is clear in the documentation that the `index` LongTensor may contain duplicate values, in which case the corresponding slices are indeed accumulated.

**Comment by soumith** [comment]
thanks Allan!

**Comment by ajabri** [comment]
My pleasure :)

On Mon, Oct 19, 2015 at 3:37 PM, Soumith Chintala <notifications@github.com>
wrote:

> thanks Allan!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/torch/torch7/pull/408#issuecomment-149322422>.
>



-- 
Thanks
Allan

**Pull request merged**
